select '-- TableNum:wt_customer.acct_wt_user_max_loss_profit';
select 'select count(1) from wt_customer.acct_wt_user_max_loss_profit ';
select count(1) from wt_customer.acct_wt_user_max_loss_profit ;
select '====================query_split====================';
select '-- wt_customer.acct_wt_user_max_loss_profit.max_loss';
select 'select fund_account, max_loss as max_value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit order by max_loss desc limit 1';
select fund_account, max_loss as max_value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit order by max_loss desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_loss as min_value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit order by max_loss asc limit 1';
select fund_account, max_loss as min_value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit order by max_loss asc limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit where max_loss is null limit 1';
select fund_account, null as value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit where max_loss is null limit 1;
select '====================query_split====================';
select '====================column_split====================';
select '-- wt_customer.acct_wt_user_max_loss_profit.max_profit';
select 'select fund_account, max_profit as max_value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit order by max_profit desc limit 1';
select fund_account, max_profit as max_value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit order by max_profit desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_profit as min_value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit order by max_profit asc limit 1';
select fund_account, max_profit as min_value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit order by max_profit asc limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit where max_profit is null limit 1';
select fund_account, null as value, """--""" as interval_type from wt_customer.acct_wt_user_max_loss_profit where max_profit is null limit 1;
select '====================query_split====================';
select '====================column_split====================';
select '====================table_split====================';
select '-- TableNum:wt_customer.acct_wt_user_max_loss';
select 'select count(1) from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628';
select count(1) from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628;
select '====================query_split====================';
select '-- wt_customer.acct_wt_user_max_loss.max_loss';
select 'select fund_account, max_loss as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1 order by max_loss desc limit 1';
select fund_account, max_loss as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1 order by max_loss desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_loss as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2 order by max_loss desc limit 1';
select fund_account, max_loss as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2 order by max_loss desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_loss as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3 order by max_loss desc limit 1';
select fund_account, max_loss as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3 order by max_loss desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_loss as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4 order by max_loss desc limit 1';
select fund_account, max_loss as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4 order by max_loss desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_loss as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1 order by max_loss asc limit 1';
select fund_account, max_loss as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1 order by max_loss asc limit 1;
select '====================query_split====================';
select 'select fund_account, max_loss as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2 order by max_loss asc limit 1';
select fund_account, max_loss as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2 order by max_loss asc limit 1;
select '====================query_split====================';
select 'select fund_account, max_loss as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3 order by max_loss asc limit 1';
select fund_account, max_loss as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3 order by max_loss asc limit 1;
select '====================query_split====================';
select 'select fund_account, max_loss as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4 order by max_loss asc limit 1';
select fund_account, max_loss as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4 order by max_loss asc limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1  and max_loss is null limit 1';
select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1  and max_loss is null limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2  and max_loss is null limit 1';
select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2  and max_loss is null limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3  and max_loss is null limit 1';
select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3  and max_loss is null limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4  and max_loss is null limit 1';
select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4  and max_loss is null limit 1;
select '====================query_split====================';
select '====================column_split====================';
select '-- wt_customer.acct_wt_user_max_loss.max_profit';
select 'select fund_account, max_profit as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1 order by max_profit desc limit 1';
select fund_account, max_profit as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1 order by max_profit desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_profit as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2 order by max_profit desc limit 1';
select fund_account, max_profit as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2 order by max_profit desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_profit as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3 order by max_profit desc limit 1';
select fund_account, max_profit as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3 order by max_profit desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_profit as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4 order by max_profit desc limit 1';
select fund_account, max_profit as max_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4 order by max_profit desc limit 1;
select '====================query_split====================';
select 'select fund_account, max_profit as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1 order by max_profit asc limit 1';
select fund_account, max_profit as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1 order by max_profit asc limit 1;
select '====================query_split====================';
select 'select fund_account, max_profit as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2 order by max_profit asc limit 1';
select fund_account, max_profit as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2 order by max_profit asc limit 1;
select '====================query_split====================';
select 'select fund_account, max_profit as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3 order by max_profit asc limit 1';
select fund_account, max_profit as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3 order by max_profit asc limit 1;
select '====================query_split====================';
select 'select fund_account, max_profit as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4 order by max_profit asc limit 1';
select fund_account, max_profit as min_value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4 order by max_profit asc limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1  and max_profit is null limit 1';
select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 1  and max_profit is null limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2  and max_profit is null limit 1';
select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 2  and max_profit is null limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3  and max_profit is null limit 1';
select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 3  and max_profit is null limit 1;
select '====================query_split====================';
select 'select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4  and max_profit is null limit 1';
select fund_account, null as value, interval_type from wt_customer.acct_wt_user_max_loss where part_init_date = 20190628 and interval_type = 4  and max_profit is null limit 1;
select '====================query_split====================';
select '====================column_split====================';
select '====================table_split====================';
